'use strict';
const names={company_fact:'公司资料',product:'产品资料',relationship:'合作与产业链',labour_claim:'具体劳动实践',product_claim:'产品体验'};
let records=[];
function text(tag,content,cls){const e=document.createElement(tag);e.textContent=content;if(cls)e.className=cls;return e;}
function show(){const form=new FormData(document.querySelector('#filter')),q=String(form.get('q')||'').trim().toLowerCase(),kind=String(form.get('kind')||'');const target=document.querySelector('#records');target.replaceChildren();const matches=records.filter(x=>(!kind||kind===x.kind)&&(!q||(x.company_name+' '+x.title+' '+x.description).toLowerCase().includes(q)));
 if(!matches.length){target.append(text('p','当前没有符合条件的公开记录。没有记录不表示某家公司好或坏。','empty'));return;}
 for(const row of matches){const a=text('article','','record');a.append(text('span',names[row.kind]+' · '+row.evidence+(['E0','E1','E2'].includes(row.evidence)?' · 未独立证实':' · 仅限所述范围')+(row.synthetic?' · 虚构测试':'') ,'record-tag'));a.append(text('h3',row.title));a.append(text('small',row.company_name+' · '+row.region));a.append(text('p',row.description));a.append(text('small',(row.scope||'范围未提供')+' · '+(row.period_start||'起始时间未知')+' — '+(row.period_end||'截止时间未知')));
 for(const source of row.sources){try{const url=new URL(source.url);if(url.protocol!=='https:')continue;const link=text('a',source.title+'：'+source.supports,'record-source');link.href=url.href;link.rel='noopener noreferrer';link.target='_blank';a.append(link);}catch{}}
 a.append(text('small','贡献：'+row.credit+' · 版本 '+row.version+' · ID '+row.id));target.append(a);}}
document.querySelector('#filter').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);history.replaceState(null,'','#library?'+new URLSearchParams({q:d.get('q')||'',kind:d.get('kind')||''}));show();});
(async()=>{try{const r=await fetch('data/dataset.json');if(!r.ok)throw Error('无法加载公开快照');const d=await r.json();records=Object.entries(d.categories).flatMap(([kind,rows])=>rows.map(row=>({...row,kind})));document.querySelector('#dataset-meta').textContent=records.length+' 条获准再分发记录 · 快照日期 '+d.generated_at.slice(0,10);const params=new URLSearchParams(location.hash.split('?')[1]||'');document.querySelector('[name=q]').value=params.get('q')||'';document.querySelector('[name=kind]').value=params.get('kind')||'';show();}catch(err){document.querySelector('#dataset-meta').textContent='资料暂时不可用';document.querySelector('#records').append(text('p','未能读取公开资料。不会用演示统计冒充实际数据。','empty'));}})();
