import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {bootstrapInstance} from '../instance/bootstrap.mjs';
import {createIndependentApp,loadInstanceBundle} from '../instance/start.mjs';
import {exportFederationSnapshot} from './export.mjs';
import {packageSignedSnapshot} from './package.mjs';
import {publishPackageToMirrors} from './publish-mirrors.mjs';
import {createPeerDescriptor} from './descriptor.mjs';
import {trustPeer} from './trust-peer.mjs';
import {pullTrustedPeer} from './pull-peer.mjs';
import {loadPeerContext} from './peer-store.mjs';
import {buildPeerDescriptor,fetchPeerMirrorIndex} from '../../sites-app/src/peer-discovery.mjs';
import {publicKeyFingerprint} from '../../sites-app/src/federation.mjs';
import {readMirrorIndex} from '../../sites-app/src/snapshot-mirror.mjs';

class Client{
  constructor(base){this.base=base;this.cookie='';this.csrf=''}
  async request(url,{method='GET',body,token}={}){const headers={Accept:'application/json'};if(this.cookie)headers.Cookie=this.cookie;if(body!==undefined){headers['Content-Type']='application/json';headers.Origin=this.base;if(this.csrf)headers['X-Ltp-Csrf']=this.csrf;}if(token)headers.Authorization=`Bearer ${token}`;const res=await fetch(this.base+url,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const set=res.headers.get('set-cookie');if(set)this.cookie=set.split(';')[0];const data=await res.json().catch(()=>({}));return {status:res.status,data};}
  async config(){const out=await this.request('/api/config');assert.equal(out.status,200);this.csrf=out.data.csrfToken;return out.data}
}
async function listenApp(app){await new Promise((resolve,reject)=>{app.server.once('error',reject);app.server.listen(0,'127.0.0.1',resolve)});return `http://127.0.0.1:${app.server.address().port}`;}
async function close(server){if(server?.listening)await new Promise(resolve=>server.close(resolve));}
async function staticServer(root){const base=path.resolve(root);const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1');const rel=decodeURIComponent(u.pathname).replace(/^\/+/, '');if(rel.split('/').includes('..')){res.writeHead(403);return res.end()}const file=path.resolve(base,rel);if(file!==base&&!file.startsWith(base+path.sep)){res.writeHead(403);return res.end()}const stat=await fs.stat(file);if(!stat.isFile()){res.writeHead(404);return res.end()}const data=await fs.readFile(file);res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Content-Length':String(data.length)});res.end(data);}catch{res.writeHead(404);res.end();}});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve)});return {server,url:`http://127.0.0.1:${server.address().port}`,root:base};}
async function runCommand(args){const child=spawn(process.execPath,args,{stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);const status=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',code=>resolve(code));});return {status,stdout,stderr};}
function claimPayload(companyId,description){return {companyId,kind:'labour_claim',title:'Peer 拉取工资实践',description,scope:'示例公开岗位',periodStart:'2026-01-01',periodEnd:'2026-12-31',direction:'negative',dimension:'pay',productId:'',brandId:'',relationType:'',relation:'',category:'',sources:[{url:'https://example.org/peer-evidence',title:'Peer 公开证据',type:'public_record',publishedAt:'2026-09-01',supports:'仅支持这条示例工资实践主张'}],public:true,consent:true,shareConsent:true,rights:'own_summary',rightsNote:'',creditName:'Peer 测试贡献者'};}
async function approve(client,bundle,id,version){let out=await client.request(`/api/contributions/${id}/review`,{method:'POST',token:bundle.secrets.reviewToken,body:{version,decision:'approve',evidence:'E3',rationale:'已核对来源、时间、范围，只支持本条公开劳动主张。',scopeChecked:true,authenticityChecked:true,sourceIds:['S1']}});assert.equal(out.status,200,JSON.stringify(out.data));out=await client.request(`/api/contributions/${id}/approve-export`,{method:'POST',token:bundle.secrets.exportToken,body:{version,privacyChecked:true,rightsChecked:true,reason:'确认当前公开摘要允许非商业公益再分发且不含私人信息。'}});assert.equal(out.status,200,JSON.stringify(out.data));}
async function exportPackagePublish(sourceDir,root,label,mirrors){const snapshot=await exportFederationSnapshot({dir:sourceDir,out:path.join(root,`${label}.snapshot.json`)});const pkg=await packageSignedSnapshot({snapshotFile:snapshot.target,outRoot:path.join(root,'packages')});await publishPackageToMirrors({packageDir:pkg.packageDir,mirrorRoots:mirrors});return {snapshot,pkg};}


test('explicitly trusted peer descriptor pulls and catches up signed snapshot chain across damaged mirrors',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'ltp-peer-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const sourceDir=path.join(root,'source'),receiverDir=path.join(root,'receiver'),attackerDir=path.join(root,'attacker');await bootstrapInstance({dir:sourceDir,name:'Peer 来源实例'});await bootstrapInstance({dir:receiverDir,name:'Peer 接收实例'});await bootstrapInstance({dir:attackerDir,name:'Peer 攻击密钥实例'});const sourceBundle=await loadInstanceBundle({dir:sourceDir});const attackerBundle=await loadInstanceBundle({dir:attackerDir});
  const mirrorDirs=[path.join(root,'mirror-a'),path.join(root,'mirror-b')];for(const d of mirrorDirs)await fs.mkdir(d,{recursive:true});const descriptorDir=path.join(root,'descriptor');await fs.mkdir(descriptorDir,{recursive:true});const mirrorServers=[await staticServer(mirrorDirs[0]),await staticServer(mirrorDirs[1])];const descriptorServer=await staticServer(descriptorDir);t.after(()=>close(mirrorServers[0].server));t.after(()=>close(mirrorServers[1].server));t.after(()=>close(descriptorServer.server));const mirrorUrls=mirrorServers.map(x=>`${x.url}/public-evidence`);const descriptorUrl=`${descriptorServer.url}/peer.json`;
  const appA=await createIndependentApp({dir:sourceDir});t.after(()=>close(appA.server));const baseA=await listenApp(appA);const a=new Client(baseA);await a.config();const company=await a.request('/api/companies',{method:'POST',body:{name:'Peer 联邦公司',region:'示例地区',website:'',consent:true}});const companyId=company.data.company.id;const claim=await a.request('/api/contributions',{method:'POST',body:claimPayload(companyId,'Peer v1 公开劳动证据。')});const claimId=claim.data.item.id;await approve(a,sourceBundle,claimId,1);
  const first=await exportPackagePublish(sourceDir,root,'s1',mirrorDirs);const d1=await createPeerDescriptor({dir:sourceDir,packageDir:first.pkg.packageDir,mirrorUrls,out:path.join(descriptorDir,'peer.json'),generatedAt:'2026-09-17T03:10:00.000Z'});assert.equal(d1.descriptor.latest.snapshotRoot,first.snapshot.snapshot.snapshotRoot);
  const publicDescriptorText=JSON.stringify(d1.descriptor);for(const secret of [sourceBundle.secrets.sessionSecret,sourceBundle.secrets.reviewToken,sourceBundle.secrets.exportToken,sourceBundle.secrets.advisoryAgentToken,sourceBundle.secrets.communityAgentToken,sourceBundle.secrets.signingPrivateKey.value])assert.equal(publicDescriptorText.includes(secret),false,'public peer descriptor must not leak private instance secret material');
  await assert.rejects(()=>trustPeer({dir:receiverDir,descriptorInput:descriptorUrl,trust:false}),/--trust/);const trusted=await trustPeer({dir:receiverDir,descriptorInput:descriptorUrl,trust:true});assert.equal(trusted.peer.instanceId,sourceBundle.instance.id);assert.equal(trusted.peer.keyFingerprint,publicKeyFingerprint(sourceBundle.instance.publicKey));
  if(process.platform!=='win32')assert.equal((await fs.stat(trusted.file)).mode&0o077,0,'peer trust store must be owner-private');
  await assert.rejects(()=>pullTrustedPeer({dir:receiverDir,peerId:sourceBundle.instance.id}),/--service-stopped/);const pull1=await pullTrustedPeer({dir:receiverDir,peerId:sourceBundle.instance.id,serviceStoppedConfirmed:true});assert.equal(pull1.chainLength,1);assert.equal(pull1.targetRoot,first.snapshot.snapshot.snapshotRoot);
  let appB=await createIndependentApp({dir:receiverDir});let baseB=await listenApp(appB);let b=new Client(baseB);await b.config();let fed=await b.request('/api/federation/evidence');assert.equal(fed.data.items.length,1);assert.equal(fed.data.items[0].sourceVersion,1);await close(appB.server);

  let edited=await a.request(`/api/contributions/${claimId}`,{method:'PATCH',body:claimPayload(companyId,'Peer v2 公开劳动证据。')});await approve(a,sourceBundle,claimId,edited.data.item.version);await new Promise(r=>setTimeout(r,3));const second=await exportPackagePublish(sourceDir,root,'s2',mirrorDirs);
  edited=await a.request(`/api/contributions/${claimId}`,{method:'PATCH',body:claimPayload(companyId,'Peer v3 公开劳动证据。')});await approve(a,sourceBundle,claimId,edited.data.item.version);await new Promise(r=>setTimeout(r,3));const third=await exportPackagePublish(sourceDir,root,'s3',mirrorDirs);assert.equal(third.snapshot.snapshot.previousRoot,second.snapshot.snapshot.snapshotRoot);assert.equal(second.snapshot.snapshot.previousRoot,first.snapshot.snapshot.snapshotRoot);
  const d3=await createPeerDescriptor({dir:sourceDir,packageDir:third.pkg.packageDir,mirrorUrls,out:path.join(descriptorDir,'peer.json'),generatedAt:'2026-09-17T03:12:00.000Z'});assert.equal(d3.descriptor.latest.snapshotRoot,third.snapshot.snapshot.snapshotRoot);
  const {index:indexA}=await readMirrorIndex(mirrorDirs[0]);const e2=indexA.entries.find(x=>x.snapshotRoot===second.snapshot.snapshot.snapshotRoot);assert.ok(e2);await fs.appendFile(path.join(mirrorDirs[0],'public-evidence',e2.packagePath,e2.snapshotFile),'\nBROKEN-MIRROR-A\n');
  const pull3=await pullTrustedPeer({dir:receiverDir,peerId:sourceBundle.instance.id,serviceStoppedConfirmed:true,refreshDescriptor:true});assert.equal(pull3.chainLength,2);assert.deepEqual(pull3.imports.map(x=>x.snapshotRoot),[second.snapshot.snapshot.snapshotRoot,third.snapshot.snapshot.snapshotRoot]);assert.ok(pull3.imports.some(x=>x.mirrorFailures.length>=1),'damaged mirror should be recorded while healthy mirror completes the chain');
  appB=await createIndependentApp({dir:receiverDir});baseB=await listenApp(appB);b=new Client(baseB);await b.config();fed=await b.request('/api/federation/evidence');assert.equal(fed.data.items[0].sourceVersion,3);assert.match(fed.data.items[0].record.claim.description,/v3/);await close(appB.server);
  const upToDate=await pullTrustedPeer({dir:receiverDir,peerId:sourceBundle.instance.id,serviceStoppedConfirmed:true});assert.equal(upToDate.status,'UP_TO_DATE');assert.equal(upToDate.chainLength,0);

  const tampered=structuredClone(d3.descriptor);tampered.mirrors[0].publicEvidenceBaseUrl='http://127.0.0.1:9/public-evidence';const tamperedFile=path.join(root,'tampered-peer.json');await fs.writeFile(tamperedFile,JSON.stringify(tampered));await assert.rejects(()=>trustPeer({dir:receiverDir,descriptorInput:tamperedFile,trust:true}),/(descriptorRoot|签名)/);
  await fs.writeFile(path.join(root,'old-peer.json'),JSON.stringify(d1.descriptor));await assert.rejects(()=>trustPeer({dir:receiverDir,descriptorInput:path.join(root,'old-peer.json'),trust:true}),/时间倒退/);
  const fakeInstance={...attackerBundle.instance,id:sourceBundle.instance.id,name:sourceBundle.instance.name};const fakeManifest={...third.pkg.manifest,sourceInstanceId:fakeInstance.id,sourceInstanceName:fakeInstance.name,sourceKeyFingerprint:publicKeyFingerprint(fakeInstance.publicKey)};const rotated=buildPeerDescriptor({instance:fakeInstance,signingPrivateKey:attackerBundle.secrets.signingPrivateKey,latestManifest:fakeManifest,mirrorUrls,generatedAt:'2026-09-17T03:13:00.000Z'});const rotatedFile=path.join(root,'rotated-peer.json');await fs.writeFile(rotatedFile,JSON.stringify(rotated));await assert.rejects(()=>trustPeer({dir:receiverDir,descriptorInput:rotatedFile,trust:true}),/公钥发生变化/);
  await assert.rejects(()=>fetchPeerMirrorIndex('https://example.invalid/public-evidence',{allowNetwork:false}),/allowNetwork/);await assert.rejects(()=>createPeerDescriptor({dir:sourceDir,packageDir:third.pkg.packageDir,mirrorUrls:['http://192.168.1.20/public-evidence'],out:path.join(root,'bad.json')}),/只允许 HTTPS/);
  const peerCtx=await loadPeerContext(receiverDir);const peer=peerCtx.store.peers.find(x=>x.instanceId===sourceBundle.instance.id);assert.equal(peer.lastPulledSnapshotRoot,third.snapshot.snapshot.snapshotRoot);assert.equal(peer.descriptor.latest.snapshotRoot,third.snapshot.snapshot.snapshotRoot);
});


test('peer descriptor/trust/pull CLIs work without central registry',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'ltp-peer-cli-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const source=path.join(root,'source'),receiver=path.join(root,'receiver'),mirror=path.join(root,'mirror'),descDir=path.join(root,'desc');await bootstrapInstance({dir:source,name:'CLI Peer 来源'});await bootstrapInstance({dir:receiver,name:'CLI Peer 接收'});await fs.mkdir(mirror,{recursive:true});await fs.mkdir(descDir,{recursive:true});const mirrorServer=await staticServer(mirror);const descServer=await staticServer(descDir);t.after(()=>close(mirrorServer.server));t.after(()=>close(descServer.server));
  const exported=await exportFederationSnapshot({dir:source,out:path.join(root,'empty.snapshot.json')});const pkg=await packageSignedSnapshot({snapshotFile:exported.target,outRoot:path.join(root,'packages')});await publishPackageToMirrors({packageDir:pkg.packageDir,mirrorRoots:[mirror]});
  const descriptorScript=new URL('./descriptor.mjs',import.meta.url),trustScript=new URL('./trust-peer.mjs',import.meta.url),pullScript=new URL('./pull-peer.mjs',import.meta.url);let run=await runCommand([descriptorScript.pathname,'--dir',source,'--package',pkg.packageDir,'--mirror-url',`${mirrorServer.url}/public-evidence`,'--out',path.join(descDir,'peer.json'),'--generated-at','2026-09-17T03:20:00.000Z']);assert.equal(run.status,0,run.stderr);const descriptorSummary=JSON.parse(run.stdout.trim());
  run=await runCommand([trustScript.pathname,'--dir',receiver,'--descriptor',`${descServer.url}/peer.json`]);assert.notEqual(run.status,0);assert.match(run.stderr,/--trust/);run=await runCommand([trustScript.pathname,'--dir',receiver,'--descriptor',`${descServer.url}/peer.json`,'--trust']);assert.equal(run.status,0,run.stderr);assert.equal(JSON.parse(run.stdout.trim()).latestSnapshotRoot,descriptorSummary.latestSnapshotRoot);
  run=await runCommand([pullScript.pathname,'--dir',receiver,'--peer',descriptorSummary.instanceId]);assert.notEqual(run.status,0);assert.match(run.stderr,/--service-stopped/);run=await runCommand([pullScript.pathname,'--dir',receiver,'--peer',descriptorSummary.instanceId,'--service-stopped']);assert.equal(run.status,0,run.stderr);const pulled=JSON.parse(run.stdout.trim());assert.equal(pulled.status,'PULL_PASS');assert.equal(pulled.chainLength,1);assert.equal(pulled.targetRoot,descriptorSummary.latestSnapshotRoot);
});
