/* Community pages extend the existing design system; no second client-side database. */
const CONTRIBUTION_KINDS={product:'产品资料',company_fact:'公司资料',relationship:'合作与产业链',labour_claim:'具体劳动实践',product_claim:'产品体验'};
const DIMENSIONS={pay:'薪资兑现',rest:'休息休假',hours:'工作时长',safety:'劳动安全',contract:'合同保障',respect:'尊重与管理',representation:'劳动者表达',other:'其他'};
const CONTRIBUTION_STATUS={PENDING:'待核验',REVIEWED:'证据状态已复核',VERIFIED:'范围内已核验',DISPUTED:'存在争议',REJECTED:'已撤下',WITHDRAWN:'作者已撤回'};
const LANES={community_positive:'社区好评 · 公司与产品',community_negative:'社区差评 · 公司与产品',evidence_positive:'证据支持 · 正向劳动实践'};
function contributionTag(x){return badge(x.evidence+' · '+(CONTRIBUTION_STATUS[x.status]||x.status),x.status==='VERIFIED'?'green':x.status==='DISPUTED'?'amber':'blue');}
function contributionRow(x){return `<article class="contribution-row"><div><span class="quiet small-text">${CONTRIBUTION_KINDS[x.kind]} · ${esc(x.credit_name)}</span><h3><a href="#contribution/${x.id}">${esc(x.title)}</a></h3><p>${esc(x.description.slice(0,150))}${x.description.length>150?'…':''}</p><p class="hint">${esc(x.scope||'范围待补充')} ${x.period_start?` · ${esc(x.period_start)} — ${esc(x.period_end||'未填写')}`:''}</p></div><div>${contributionTag(x)}<p class="small-text quiet">${x.sources.length} 个来源 · 版本 ${x.version}</p><a class="text-link" href="#contribution/${x.id}">查看依据与贡献</a></div></article>`;}
async function discoverPage(params){
 if(!cap('showcase'))return `<div class="wrap">${head('公司与产品，一起看清楚。','展示区将在社区阶段开放。公司登记与共建资料现在就可以开始。')}<div class="narrow">${empty('准备开放','不以资料不足阻止讨论；热度与证据始终分开。','#contribute','先来补充资料')}</div></div>`;
 const lane=LANES[params.get('lane')]?params.get('lane'):'community_positive';const q=params.get('q')||'';const days=['7','30','90'].includes(params.get('days'))?params.get('days'):'7';
 const d=await api('/showcase?'+new URLSearchParams({lane,q,days}));
 return `<div class="wrap discover"><section class="discover-head"><div><a class="crumb" href="#home">首页 /</a><h1>选择之前，<br>看见公司与产品的另一面。</h1><p>大家怎样评价，材料支持什么。把两件事分开，选择才更清楚。</p></div><a class="button primary" href="#contribute">贡献一条信息 ${icon('arrow')}</a></section>
 <nav class="discovery-tabs" aria-label="公司与产品展示分区">${Object.entries(LANES).map(([k,v])=>`<a ${k===lane?'aria-current="page"':''} href="#discover?${new URLSearchParams({lane:k,q,days})}">${v}</a>`).join('')}</nav>
 <form id="discovery-search" class="discovery-search"><input type="hidden" name="lane" value="${lane}">${field('搜索公司、产品或地区','q','输入你关心的名字','search',false,q,100)}${select('观察时间','days',{'7':'最近7天','30':'最近30天','90':'最近90天'},days)}<button type="submit">查找</button></form>
 <div class="discovery-method"><p>${lane==='evidence_positive'?'只展示当前有效、E3及以上的具体正向劳动实践，不颁发“全公司优质”认证。':'按参与账号数排序，正负票多数决定所在分区。E0也可以有很高热度。'}</p><span>资料更新于 ${date(d.updated_at)}</span></div>
 <section aria-label="展示结果">${d.items.map((x,i)=>`<article class="discovery-company"><div class="discovery-number">${String(i+1).padStart(2,'0')}</div><div class="discovery-main"><div class="section-head"><div><p class="quiet small-text">${esc(x.company.region)}${x.company.synthetic?' · 虚构演示公司':''}</p><h2><a href="#company/${x.company.id}">${esc(x.company.name)}</a></h2></div>${badge('分项查看证据，不给公司整体盖章','blue')}</div><div class="discovery-counts"><span><strong>${x.participants}</strong> 参与账号</span><span><strong>${x.positive}</strong> 正面票</span><span><strong>${x.negative}</strong> 负面票</span>${x.small_sample?'<span class="sample-note">投票样本少，仅供参考</span>':''}</div>
 ${x.verified_positive_claims.length?`<div class="verified-practices"><h3>有证据支持的具体实践</h3>${x.verified_positive_claims.map(c=>`<p><a class="text-link" href="#contribution/${c.id}">${esc(c.title)}</a> ${contributionTag(c)}<small>${esc(c.scope)} · ${esc(c.period_start)} — ${esc(c.period_end)}</small></p>`).join('')}</div>`:''}
 <div class="discovery-products"><h3>相关产品 <span>${x.products.length}项共建记录</span></h3>${x.products.length?`<div class="product-strip">${x.products.map(p=>`<a class="product-item" href="#contribution/${p.id}"><span class="product-symbol" aria-hidden="true">${icon('file')}</span><strong>${esc(p.title)}</strong><span>${esc(p.category||'产品资料')}</span>${contributionTag(p)}</a>`).join('')}</div>`:'<p class="quiet">还没有产品资料。知道一些线索，也可以从E0开始补充。</p>'}</div>
 ${x.other_claims.length?`<p class="hint">另有 ${x.other_claims.length} 项其他或不同时期主张，<a href="#company/${x.company.id}/community-data">查看完整上下文</a>。</p>`:''}
 <div class="actions"><a class="text-link" href="#company/${x.company.id}">了解公司</a><a class="text-link" href="#contribute/${x.company.id}">补充公司或产品资料</a></div></div></article>`).join('')||empty('这个分区还没有符合条件的记录','没有记录不代表公司好或坏。你可以添加公司，或补充自己知道的信息。','#contribute','参与共建')}</section>
 <aside class="discovery-footnote"><h2>每一份贡献，都有来处。</h2><p>${esc(d.limits)}</p><p>公开展示不等于允许再分发。只有分别取得授权并完成隐私、版权复核的资料，才进入公益数据包。</p><a class="text-link" href="#data">查看公益数据与贡献说明</a></aside></div>`;
}
async function contributePage(cid='',editId=''){
 const companies=await api('/companies');let existing=null;
 if(editId){existing=await api('/contributions/'+editId);cid=existing.company_id;if(!existing.is_mine)throw Error('只能修改自己的贡献');}
 if(cid&&!companies.some(c=>c.id===cid)){companies.push(await api('/companies/'+cid));}
 const p=existing||{};const choices=Object.fromEntries(companies.map(c=>[c.id,c.name]));
 if(!companies.length)return `<div class="wrap">${head('一起补充，让信息更完整。','没有附件也能贡献。先为你关心的公司建立一个空间。')}${empty('先添加一家公司','公司空间建立后就能补充资料，不需要等待Agent。','#register','添加公司')}</div>`;
 return `<div class="wrap">${head(existing?'更新这条贡献':'一起补充，让信息更完整。','一个产品名称，一份公开资料，一段具体经历，都能帮助后来的人。')}<div class="contribute-layout"><form id="contribution-form" class="form-panel" data-edit="${editId}" data-version="${p.version||1}">
 ${select('对应公司','company_id',choices,cid||companies[0].id)}<p class="hint">没有找到？<a href="#register">先添加公司</a>。重名公司请先核对地区。</p>
 ${select('你要补充哪类信息？','kind',CONTRIBUTION_KINDS,p.kind||'product')}${field('资料标题或产品名称','title','例如：示例电动工具的生产公司','text',true,p.title||'',120)}
 ${textarea('你知道什么？','description','用自己的话说明，只写你知道的部分。',2000,p.description||'')}
 <div class="form-grid">${field('产品类别（可选）','category','例如：家用电器','text',false,p.category||'',80)}${field('关系类型（可选）','relation','例如：品牌拥有者、生产制造商','text',false,p.relation||'',80)}</div>
 ${select('主张方向','direction',{neutral:'中性资料',positive:'正向实践或体验',negative:'需要留意的问题'},p.direction||'neutral')}${select('具体领域','dimension',DIMENSIONS,p.dimension||'other')}
 ${field('覆盖范围（可选）','scope','例如：某地工厂公开制度，不代表所有部门','text',false,p.scope||'',300)}<div class="form-grid">${field('资料适用起日（可选）','period_start','','date',false,p.period_start||'')}${field('资料适用止日（可选）','period_end','','date',false,p.period_end||'')}</div>
 ${field('产品记录ID（仅产品体验必填）','product_id','从产品详情页复制记录ID','text',false,p.product_id||'',80)}
 <details ${p.sources?.length?'open':''}><summary>补充公开来源（可选，最多10项）</summary><p class="hint">无来源可以提交E0。网址不会自动访问；核验员会分别核对来源支持了什么。</p>${field('来源网址','source_url','https://公开来源地址','url',false,p.sources?.[0]?.url||'',500)}${field('来源标题','source_title','例如：企业产品介绍','text',false,p.sources?.[0]?.title||'',200)}${select('来源类别','source_type',{other:'其他公开来源',company_disclosure:'企业披露',public_record:'公开记录',official_decision:'正式认定文件',first_person:'亲历说明'},p.sources?.[0]?.type||'other')}${field('来源发布日期','source_date','','date',false,p.sources?.[0]?.published_at||'')}${textarea('这个来源支持哪一部分？','source_supports','不要把历史名单说成当前合作。',1000,p.sources?.[0]?.supports||'',false)}<p class="hint">需要多个来源可使用下方JSON导入；编辑时保留原有其他来源。</p></details>
 <fieldset class="contribution-consent"><legend>由你决定公开和授权范围</legend><label class="check"><input name="public" type="checkbox" ${p.public?'checked':''}>在公司空间公开这段资料。未核验时标记为E0。</label><label class="check"><input name="share_consent" type="checkbox" ${p.share_consent?'checked':''}>另行允许经复核的安全版本，按公益专用许可再分发；我理解已下载副本可能无法收回。</label>${select('这段说明的使用权来源','rights',{reference_only:'只作参考，不授权再分发',own_summary:'本人原创整理或改写',permission:'已取得明确再分发授权',public_domain:'已核对属于公有领域'},p.rights||'reference_only')}${field('授权依据说明（取得许可时必填）','rights_note','','text',false,p.rights_note||'',500)}${field('公开贡献署名（可选）','credit_name','不填则使用“匿名贡献者”；不要填写真实私人信息','text',false,p.credit_name==='匿名贡献者'?'':p.credit_name||'',40)}<label class="check"><input name="consent" type="checkbox" required>我已检查公开范围，不上传他人隐私，也不授予自己没有的权利。</label></fieldset>
 ${err()}<button class="primary" type="submit">${existing?'保存新版本，重新核验':'提交这条贡献'}</button></form>
 <aside class="contribution-guide"><h2>信息由社区一起维护</h2><p>没有来源，也能提供线索。附件数量、点赞数或贡献次数，不会自动提升证据等级。</p><h3>三件事分开决定</h3><p>你决定是否公开。核验员记录证据支持范围。另一名核验员检查是否适合公益再分发。</p><h3>可以更正，也可以撤回</h3><p>修改会生成新版本，证据等级重新核验。撤回后停止在本平台展示和后续数据导出。</p><a class="text-link" href="#contributions">我的贡献</a><details><summary>批量上传JSON资料</summary><form id="contribution-batch"><label class="field">选择JSON文件（最多50条，1MB）<input name="file" type="file" accept=".json,application/json" required></label><p class="hint">文件格式为 {"items": [...]}。每条必须明确公司、公开范围和授权，系统不会替你勾选同意。</p>${err()}<button type="submit">检查并导入</button></form></details></aside></div></div>`;
}
async function contributionsPage(){const d=await api('/contributions?mine=true');return `<div class="wrap">${head('我的贡献','每一条都有版本、证据状态和公开范围。你可以继续补充或撤回。')}<div class="actions"><a class="button primary" href="#contribute">贡献信息</a><a class="button" href="#mine">我的空间</a></div><div class="panel">${d.map(x=>contributionRow(x)).join('')||empty('还没有提交资料','从一个你知道的产品或公开来源开始。')}</div></div>`;}
async function contributionDetail(id){const p=await api('/contributions/'+id);return `<div class="wrap">${head(p.title,`${CONTRIBUTION_KINDS[p.kind]} · ${esc(p.credit_name)} · 版本 ${p.version}`,'#company/'+p.company_id+'/community-data','公司共建资料')}<div class="reading"><p>${contributionTag(p)} ${badge(p.public?'公开展示':'仅本人可见')}</p><p class="body-text">${esc(p.description)}</p><p><strong>范围：</strong>${esc(p.scope||'尚未说明')}<br><strong>适用期间：</strong>${esc(p.period_start||'未知')} — ${esc(p.period_end||'未知')}</p><p class="hint">记录ID：${esc(p.id)}。公司评价与产品品质是独立事项，不能互相替代。</p><h2>来源与支持范围</h2>${p.sources.map(s=>`<section class="fact"><a class="text-link" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a><p>${esc(s.supports)}</p><p class="hint">${esc(s.id)} · ${esc(s.published_at||'日期待核对')}</p></section>`).join('')||'<p>尚无来源。这条信息仍可以被讨论，但没有独立验证。</p>'}<h2>核验与更正记录</h2>${p.reviews.map(r=>`<p>${esc(r.evidence)} · ${esc(r.rationale)}<small class="hint">${date(r.created_at)}</small></p>`).join('')||'<p>当前版本尚无核验记录。</p>'}<p class="notice">${p.export_approved?'这个版本已通过独立的公益再分发复核。':'这条内容未进入公益开放数据包。公开展示不等于可以任意转载原件。'}</p>${p.is_mine?`<div class="actions"><a class="button" href="#edit-contribution/${p.id}">补充／更正资料</a><button data-action="withdraw-contribution" data-id="${p.id}">撤回贡献</button></div>`:`<details><summary>指出错误或隐私问题</summary><form id="flag-contribution" data-id="${p.id}">${textarea('需要核对什么？','reason','这段反馈仅向核验人员展示。',1000)}${err()}<button type="submit">提交私密纠错</button></form></details>`}</div></div>`;}
async function companyContributions(cid){const rows=await api('/contributions?company_id='+encodeURIComponent(cid));return `<div class="actions"><a class="button primary" href="#contribute/${cid}">补充公司／产品资料</a><a class="button" href="#discover">浏览公司与产品</a></div><div class="panel">${rows.map(contributionRow).join('')||empty('资料等你一起补充','公司信息暂缺不妨碍讨论；没有附件也能上传线索。')}</div>`;}
async function dataPage(){const d=await api('/public-data');return `<div class="wrap">${head('把安全的信息，留给需要的人。','代码公开供公益协作。经授权与独立复核的资料，分类提供公益再利用。')}<article class="reading"><h2>当前可再分发 ${d.record_count} 条记录</h2><div class="data-categories">${Object.entries(d.categories).map(([k,v])=>`<div><strong>${v.length}</strong><span>${CONTRIBUTION_KINDS[k]}</span></div>`).join('')}</div><div class="actions"><a class="button primary" href="/api/public-data/download" download>下载公益数据JSON</a><a class="button" href="#contributions">查看我的贡献</a></div><h2>不是把整个数据库放上网</h2><p>数据包只包含批准的资料说明、来源链接、适用范围、证据状态和自愿署名。不含账号标识、投诉人信息、私密材料、原始附件或私人纠错内容。</p><h2>仅限非商业公益用途</h2><p>允许为劳动权益保护、公共教育和非商业公益研究查阅、修改和分享。禁止商业化、付费转售、广告营销、商业模型训练及其他非公益使用。衍生版本须保留许可和贡献说明。第三方原文与商标不属于本项目可随意授权的内容。</p><p>这一安排是“公益用途源码公开”，不是允许商业使用的OSI开源许可。许可文本仍需正式法律审阅；不保证能控制所有网络副本。</p><a class="text-link" href="/assets/public-interest-license.txt">阅读公益用途许可</a><h2>贡献如何记录？</h2><p>每条资料保留新增类型、版本、来源及核验结果；只有你自愿填写的公开署名会展示，不以账号、钱包或真实身份建立贡献排行榜。</p><h2>撤回与更正</h2><p>${esc(d.withdrawal_notice)}</p><div class="panel">${Object.values(d.categories).flat().map(x=>`<div class="mini-row"><a href="#contribution/${x.id}">${esc(x.title)}</a><small>${esc(x.credit)} · ${x.evidence} · 版本 ${x.version}</small></div>`).join('')||'<p class="content-pad">当前没有获批数据。不会使用虚构数字冒充真实社区贡献。</p>'}</div></article></div>`;}
async function reviewPage(){const role=await api('/review-role');if(!role.can_review)return `<div class="wrap">${head('资料核验工作台','需项目运营授权的核验员账号。')}<div class="narrow">${empty('当前账号没有核验权限','普通成员仍然可以发帖、上传资料和提出纠错。','#contribute','贡献信息')}</div></div>`;const rows=await api('/review-queue');return `<div class="wrap">${head('资料核验工作台','只处理已选择公开的版本；不能核验自己的贡献。数据再分发另需第二人复核。')}<div class="review-list">${rows.map(p=>`<section class="panel content-pad">${contributionRow(p)}${(p.pending_flags||[]).length?`<aside class="notice warning"><h4>待处理私密纠错</h4>${p.pending_flags.map(f=>`<p>${esc(f.reason)}</p>`).join('')}<p>核验说明需要明确回应上述问题；纠错人的身份不会公开。</p></aside>`:''}<details><summary>核验版本 ${p.version}</summary><form class="contribution-review-form" data-id="${p.id}" data-version="${p.version}">${select('核验决定','decision',{approve:'记录核验结论',dispute:'记录争议',reject:'按具体理由撤下',reopen:'退回待核验'})}${select('对应证据等级','evidence',{E0:'E0 用户陈述',E1:'E1 具体经历',E2:'E2 材料已收到',E3:'E3 范围内获得支持',E4:'E4 公开可核验依据',E5:'E5 相关正式认定'})}${textarea('本次核验依据与边界','rationale','必须说明资料支持什么、不支持什么。',1000)}${field('支持主张的来源ID，逗号分隔','source_ids','例如：S1,S2','text',false)}${field('正式决定编号（E5必填）','decision_reference','','text',false)}<label class="check"><input type="checkbox" name="scope_checked">已核对主张范围、时间与来源对应关系</label><label class="check"><input type="checkbox" name="authenticity_checked">已独立核对来源真实性，不只是看见链接</label><label class="check"><input type="checkbox" name="effective">正式决定当前具有相关效力（E5）</label>${err()}<button type="submit">保存核验记录</button></form></details><details><summary>第二人：公益再分发复核</summary><form class="contribution-export-form" data-id="${p.id}" data-version="${p.version}"><p class="hint">当前授权：${p.share_consent?'用户允许公益再分发':'未授权再分发'} · ${esc(p.rights_note||p.rights||'')}</p><label class="check"><input type="checkbox" name="privacy_checked" required>已检查组合识别风险与公开字段</label><label class="check"><input type="checkbox" name="rights_checked" required>已核对版权与公益再分发授权</label>${textarea('复核依据','reason','由不同于作者和事实核验者的人完成。',1000)}${err()}<button type="submit">批准当前版本进入公益数据包</button></form></details></section>`).join('')||empty('没有待核验资料','私密事项不会出现在这里。')}</div></div>`;}

async function submitCommunityForm(form,data){const v=k=>String(data.get(k)||'');
 if(form.id==='discovery-search'){location.hash='discover?'+new URLSearchParams({lane:v('lane'),q:v('q'),days:v('days')});return true;}
 if(form.id==='contribution-form'){
  const payload={};for(const k of ['company_id','kind','title','description','scope','period_start','period_end','direction','dimension','product_id','relation','category','rights','rights_note','credit_name'])payload[k]=v(k);
  for(const k of ['public','consent','share_consent'])payload[k]=data.has(k);payload.sources=[];
  if(v('source_url'))payload.sources.push({url:v('source_url'),title:v('source_title'),type:v('source_type'),published_at:v('source_date'),supports:v('source_supports')});
  let result;if(form.dataset.edit){const old=await api('/contributions/'+form.dataset.edit);payload.sources.push(...old.sources.slice(1).map(({id,...source})=>source));result=await api('/contributions/'+form.dataset.edit+'/revise',{version:Number(form.dataset.version),contribution:payload});}
  else result=await api('/contributions',payload);location.hash='contribution/'+result.id;return true;
 }
 if(form.id==='contribution-batch'){const file=data.get('file');if(!file?.size||file.size>1024*1024)throw Error('请选择1MB以内的JSON文件');let body;try{body=JSON.parse(await file.text());}catch{throw Error('文件不是有效JSON');}await api('/contributions/batch',body);location.hash='contributions';return true;}
 if(form.id==='flag-contribution'){await api('/contributions/'+form.dataset.id+'/flag',{reason:v('reason')});form.outerHTML='<p class="notice" role="status">纠错已私密提交。事实是否成立仍需核对；后续数据再分发暂缓。</p>';return true;}
 if(form.classList.contains('contribution-review-form')){await api('/contributions/'+form.dataset.id+'/review',{version:Number(form.dataset.version),decision:v('decision'),evidence:v('evidence'),rationale:v('rationale'),checks:{scope_checked:data.has('scope_checked'),authenticity_checked:data.has('authenticity_checked'),source_ids:v('source_ids').split(',').map(x=>x.trim()).filter(Boolean),decision_reference:v('decision_reference'),effective:data.has('effective')}});toast('核验记录已保存');await render();return true;}
 if(form.classList.contains('contribution-export-form')){await api('/contributions/'+form.dataset.id+'/approve-export',{version:Number(form.dataset.version),privacy_checked:data.has('privacy_checked'),rights_checked:data.has('rights_checked'),reason:v('reason')});toast('已通过当前版本的公益再分发复核');await render();return true;}
 if(form.id==='reviewer-role-form'){await adminApi('/reviewers',{username:v('username'),active:data.has('active')});toast('核验员权限已更新');return true;}
 return false;
}
