'use strict';
/* Research UI reuses the existing design system. No public-page network trigger. */
function researchProgress(progress){if(!progress)return '';return `<div class="side-note"><h3>这次资料更新</h3>${badge(progress.label,progress.state==='PUBLISHED'?'green':'')}<p class="small-text">目标公布：${date(progress.target_at)}${progress.overdue?'<br>已超过目标时间，补齐任务仍保留。':''}</p><p class="hint">${esc(progress.note)}</p></div>`;}
async function researchPage(){
 if(!adminToken)return manage();
 const data=await adminApi('/research');
 const sch=data.scheduler||{};const worker=sch.worker||{};const scheduleText=sch.active?`调度器最近心跳：${date(worker.heartbeat_at)} · ${esc(worker.mode||'')}`:'当前没有活跃调度心跳；仍可手动执行有限批次。';
 return `<div class="wrap">${head('公开资料研究','这里处理企业参考信息，不读取劳动者身份、私密申诉或原始附件。','#manage','运营工作台')}<div class="notice">来源：${esc(data.source)}。查询只产生待核对草稿，不会自行批准。${esc(scheduleText)}</div><div class="split"><section><div class="panel content-pad"><h2>队列健康</h2><p>逾期未发布：<strong>${Number(sch.overdue||0)}</strong> · 今日预留来源请求：<strong>${Number(sch.reserved_requests_today||0)}</strong></p><p class="hint">${sch.source_pause_until?'来源暂停到 '+date(sch.source_pause_until):'当前没有来源级暂停。'} 调度器只处理公开公司资料，用户申诉内容不会进入查询。</p></div><form id="research-run-form" class="form-panel"><h2>处理一个有限批次</h2><p>优先处理已结束的自然日和历史积压，不丢弃超过24小时的任务。</p>${field('本次最多处理公司数','max_jobs','','number',true,'3',2)}<label class="consent"><input name="include_current" type="checkbox">本次也包含今天的新登记（明确的即查测试，不代表次日调度已验证）。</label><label class="consent"><input name="allow_network" type="checkbox" required>允许本次向GLEIF发送公开公司名称、地区或LEI进行查询。</label>${err()}<button type="submit" class="primary" ${data.network_enabled?'':'disabled'}>查询公开资料</button>${data.network_enabled?'':'<p class="hint">启动环境未开启网络研究。可以查看旧任务与进行复核，但不能触发查询。</p>'}</form><div class="section-head"><h2>资料与待处理事项</h2><button data-action="retry">刷新状态</button></div>${data.tasks.map(researchTask).join('')||empty('目前没有真实企业研究任务','虚构演示和私密公司不会被发到外部来源。')}</section><aside><div class="side-note"><h3>先核对范围，再批准</h3><p>GLEIF只支持企业参考资料和会计合并关系；不是企业劳动评级、产品认证或完整供应链。已收到资料与已确认事实是不同状态。</p></div><div class="side-note"><h3>复核后仍按公布时间</h3><p>批准锁定本版内容，不会立刻对公众发布。到期时使用运营页的“发布已到期资料”，或以后安装的有限批次命令。</p><a href="#manage" class="text-link">返回运营工作台</a></div></aside></div></div>`;
}
function researchTask(task){const r=task.run;let action='';
 if(task.state==='NEEDS_IDENTITY'&&r?.candidates?.length)action=`<form id="bind-${task.job_id}" class="research-bind-form form-panel" data-run="${esc(r.id)}"><h3>核对企业主体</h3>${select('选择来源返回的候选','lei',Object.fromEntries(r.candidates.map(c=>[c.lei,c.name+' · '+c.country+' · '+c.lei])))}${textarea('说明匹配依据','reason','核对名称、地区、标识等，不凭名称相似合并。',1500)}${err()}<button type="submit">确认主体，重新加入查询队列</button></form>`;
 if(task.state==='DRAFT_READY'&&r?.packet)action=`<form class="research-approve-form form-panel" data-run="${esc(r.id)}" data-hash="${esc(r.packet_hash)}"><h3>核对这份草稿</h3><p class="hint">查询模式：${esc(r.mode)}。测试传输不能视为真实网络验证。</p><details open><summary>全部条目及来源</summary><pre>${esc(JSON.stringify(r.packet,null,2))}</pre></details>${[['identity_checked','主体名称和标识对应正确'],['sources_checked','已打开并核对来源支持这些条目'],['scope_checked','时间、关系类型及结论范围没有扩大'],['no_private_data','没有劳动者身份、私人联系方式或私密案件'],['license_checked','已核对上游许可及展示范围']].map(([k,v])=>`<label class="consent"><input type="checkbox" name="${k}" required>${v}</label>`).join('')}${textarea('本次复核说明','reason','记录实际检查内容；不要复制“已通过”作为依据。',1500)}${err()}<button type="submit">批准这份冻结草稿</button></form>`;
 if(['FAILED_FINAL','RETRY_WAIT'].includes(task.state))action=`<form class="research-reopen-form" data-job="${esc(task.job_id)}">${textarea('重新处理的依据','reason','例如来源恢复、已纠正标识。不反复重试明确的权限拒绝。',1500)}${err()}<button type="submit">保留记录并重新排队</button></form>`;
 return `<article class="panel content-pad section"><h3><a href="#company/${esc(task.company_id)}">${esc(task.name)}</a></h3><p>${badge(task.state)} 批次 ${esc(task.batch_day)} · 目标 ${date(task.due_at)}</p>${task.last_code?`<p class="hint">诊断：${esc(task.last_code)}。已尝试 ${task.attempts} 次。</p>`:''}${r?.reason?`<p class="small-text">${esc(r.reason)}</p>`:''}${action}</article>`;}
async function submitResearchForm(form,data){const v=k=>String(data.get(k)||'');
 if(form.id==='research-run-form'){const n=Number(v('max_jobs'));if(!Number.isInteger(n)||n<1||n>20)throw Error('每批最多处理1—20家公司');const r=await adminApi('/research/run',{allow_network:data.has('allow_network'),max_jobs:n,include_current:data.has('include_current')});toast('本次处理 '+r.runs.length+' 个任务；获取资料不等于已发布');await render();return true;}
 if(form.classList.contains('research-bind-form')){await adminApi('/research/runs/'+form.dataset.run+'/bind',{lei:v('lei'),reason:v('reason')});toast('主体关联已记录，等待重新查询');await render();return true;}
 if(form.classList.contains('research-approve-form')){const checks=Object.fromEntries(['identity_checked','sources_checked','scope_checked','no_private_data','license_checked'].map(k=>[k,data.has(k)]));await adminApi('/research/runs/'+form.dataset.run+'/approve',{expected_hash:form.dataset.hash,reason:v('reason'),checks});toast('本版已复核，等待到期公布');await render();return true;}
 if(form.classList.contains('research-reopen-form')){await adminApi('/research/jobs/'+form.dataset.job+'/reopen',{reason:v('reason')});toast('已重新排队，历史失败记录保留');await render();return true;}
 return false;
}
